version: '3.8'

services:
  mongodbaaa:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  express-app:
    build: .
    container_name: express-app
    ports:
      - "80:3000"
    depends_on:
      - mongodbaaa
    environment:
      MONGO_URL: mongodb://mongodbaaa:27017/goexpert


